version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile # Dockerfile local
    ports:
      - "3000:3000" # Exponer el puerto 3000 en el 3000
    depends_on:
      - db
    environment:
      # Example: Database connection details for your application
      DB_HOST: local_db ## el HOST dentro del docker-compose es el nombre
      ## del servicio
      DB_USER: local_myuser
      DB_PASSWORD: local_mypassword
      DB_NAME: local_mydb
  db:
    image: postgres:latest
    container_name: my_postgres_db
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: mydb
    ports:
      - "5432:5432" # Expose PostgreSQL port
    volumes:
      - postgres_data:/var/lib/postgresql/data # Persistent data storage
volumes:
  postgres_data:
