name: Node Test
run-name: Test nodejs app
on: [push, pull_request]
jobs:
  test:
    runs-on: [self-hosted]
    steps:
      - name: Descargar el repo
        uses: actions/checkout@v4
      - name: Configurar Nodejs
        uses: actions/setup-node@v4
        with:
          node-version: "22.x"
      - name: Instalar dependencias
        working-directory: calculadora
        run: |
          npm ci
      - name: Ejecutar tests unitarios
        working-directory: calculadora
        run: |
          npm test
      - name: Ejecutar tests e2e
        working-directory: calculadora
        run: |
          npm run test:e2e
      - name: Generar reporte de cobertura
        working-directory: calculadora
        run: |
          npm run test:cov
